#!/usr/bin/env python
# Builds the Crucible simulation extension.
#   scons platform=linux target=template_release
#   scons platform=windows use_mingw=yes target=template_release
# Needs godot-cpp (branch 4.5) at ./godot-cpp or at GODOT_CPP.
import os

godot_cpp = os.environ.get("GODOT_CPP", "godot-cpp")
env = SConscript(os.path.join(godot_cpp, "SConstruct"))
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "windows" and env.get("use_mingw", False):
    # Link the C++ runtime and winpthreads in, so the DLL needs nothing beside it.
    env.Append(LINKFLAGS=["-static", "-static-libgcc", "-static-libstdc++"])
elif env["platform"] == "linux":
    env.Append(LINKFLAGS=["-pthread"])
    env.Append(CCFLAGS=["-pthread"])

name = "crucible_sim.{}.{}".format(env["platform"], env["arch"])
library = env.SharedLibrary("../bin/" + name + env["SHLIBSUFFIX"], source=sources)
Default(library)
